@startuml

actor "API User" as API_USER

node "API service" as API
node "Comic book service" as COMICBOOK
node "Person service" as PERSON

API_USER <--> API : HTTP
API <--> COMICBOOK : HTTP
API <--> PERSON : HTTP
COMICBOOK <--> PERSON : Messages

@enduml
